// import 'package:flutter/material.dart';

// /* Text 1) ลงทะเบียนผู้ใช้งาน longin with user name + PW กรณีไม่ตั้งค่า Pin Code
//     Autogenerated by FlutLab FTF Generator
//   */
// // ignore: camel_case_types
// class longinPin extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return GestureDetector(
//       onTap: () => Navigator.pushNamed(context, '/login'),
//       child: Text(
//         '''kdfgdlfgd''',
//         overflow: TextOverflow.visible,
//         textAlign: TextAlign.left,
//         style: TextStyle(
//           height: 1.5,
//           fontSize: 24.0,
//           fontFamily: 'Prompt',
//           fontWeight: FontWeight.w400,
//           color: Color.fromARGB(255, 255, 255, 255),

//           /* letterSpacing: 0.24, */
//         ),
//       ),
//     );
//   }
// }