import 'package:flutter/material.dart';

/* Text จดจำไว้ในระบบ
    Autogenerated by FlutLab FTF Generator
  */
class Rember extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''จดจำไว้ในระบบ''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.5,
        fontSize: 14.0,
        fontFamily: 'IBMPlexSans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 151, 151, 151),

        /* letterSpacing: 0.14, */
      ),
    );
  }
}
