// import 'package:flutter/material.dart';

// /* Text 1) ลงทะเบียนผู้ใช้งาน longin with user name + PW กรณีไม่ตั้งค่า Pin Code
//     Autogenerated by FlutLab FTF Generator
//   */
// // ignore: camel_case_types
// class longinsername extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return GestureDetector(
//       onTap: () => Navigator.pushNamed(context, '/login'),
//       child: Text(
//         '''kdfgdlfgd''',
//         overflow: TextOverflow.visible,
//         textAlign: TextAlign.left,
//         style: TextStyle(
//           height: 1.5,
//           fontSize: 24.0,
//           fontFamily: 'Prompt',
//           fontWeight: FontWeight.w400,
//           color: Color.fromARGB(255, 255, 255, 255),

//           /* letterSpacing: 0.24, */
//         ),
//       ),
//     );
//   }
// }

 
// import 'package:flutter/material.dart';

// /* Rectangle โรงพยาบาลชัยนาทนเรนทร 1
//     Autogenerated by FlutLab FTF Generator
//   */
// mixin longinPin implements StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Container(
//       width: 327.0,
//       height: 181.0,
//       child: ClipRRect(
//         borderRadius: BorderRadius.zero,
//         child: Image.asset(
//           "assets/images/logo.png",
//           color: null,
//           fit: BoxFit.cover,
//           width: 327.0,
//           height: 181.0,
//           colorBlendMode: BlendMode.dstATop,
//         ),
//       ),
//     );
//   }
// }



